# Generated by Django 2.2.2 on 2019-06-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
